### PR TITLE
Adding hard-to-find option documenation to readme

### PR DESCRIPTION
**Pull request by krainboltgreene**
I had an issue this morning due to the default nature of the escape encoding, and had to look at C code to find out what I could do about it. This documentation should definitely be top level.

### CODE REVIEW

**Comment by ohler55** [comment]
There generated docs. Here for example http://www.ohler.com/oj/Oj.html. Click on classes and then Oj.

I can understand the desire to have the options more prominently displayed though. Having said that I don't think they need to take over the landing page. If you would like to have your PR pulled in there will have to be a number of changes. We can go that route or I can make the changes here. You choice.

If you want to proceed then first, there is no need for 2 example of the use that are almost the same in the Readme. I'd prefer to keep the example under "Simple JSON Writing and Parsing Example". Moving that example to earlier in the Readme makes sense though as does changing the heading to Using as you did.

As for the options descriptions, trying to merge values into the default_options does not work. You have to use the line give as Oj.default_options = {:mode => :compat} approach as noted in the Description section. I you would like to describe the options under the description, not as code but as an unordered list I'd be glad to include that.

**Comment by krainboltgreene** [comment]
It definitely does work. You might have looked at a previous edit where I forgot the `!`.

**Comment by ohler55** [comment]
calling Oj.default_options.merge!() will return a Hash and modify it with the merge. It will not change the Oj.default_options though. That option Hash is generated when the call is made and is a copy of what is used internally. That merge call will not modify the options in Oj.

Back to the other points though. Placing the setting of options as the first section and labeling it "Using" is not the way I want to introduce Oj. The "Using" section also conflicts with "Simple JSON Writing and Parsing Example" section later on as both effectively claim to be examples of how to use Oj.

**Comment by krainboltgreene** [comment]
Then why does it crash when I set it to use object mode? :P

**Comment by ohler55** [comment]
I have no idea why it crashes without having more information. What code are you using? Are you dumping or loading? 

As for the default options, try this and note no change in the ident value:
```ruby
irb(main):001:0> Oj.default_options
=> {:indent=>0, :second_precision=>9, :circular=>false, :class_cache=>true, :auto_define=>false, :symbol_keys=>false, :bigdecimal_as_decimal=>true, :use_to_json=>true, :nilnil=>false, :allow_gc=>true, :quirks_mode=>true, :float_precision=>15, :mode=>:object, :escape_mode=>:json, :time_format=>:unix_zone, :bigdecimal_load=>:auto, :create_id=>"json_class"}
irb(main):002:0> Oj.default_options.merge!({:indent => 3})
=> {:indent=>3, :second_precision=>9, :circular=>false, :class_cache=>true, :auto_define=>false, :symbol_keys=>false, :bigdecimal_as_decimal=>true, :use_to_json=>true, :nilnil=>false, :allow_gc=>true, :quirks_mode=>true, :float_precision=>15, :mode=>:object, :escape_mode=>:json, :time_format=>:unix_zone, :bigdecimal_load=>:auto, :create_id=>"json_class"}
irb(main):003:0> Oj.default_options
=> {:indent=>0, :second_precision=>9, :circular=>false, :class_cache=>true, :auto_define=>false, :symbol_keys=>false, :bigdecimal_as_decimal=>true, :use_to_json=>true, :nilnil=>false, :allow_gc=>true, :quirks_mode=>true, :float_precision=>15, :mode=>:object, :escape_mode=>:json, :time_format=>:unix_zone, :bigdecimal_load=>:auto, :create_id=>"json_class"}
irb(main):004:0>
```

**Comment by krainboltgreene** [comment]
Well don't I feel red in the face, looks like we changed it recently:

``` ruby
Oj.default_options = Oj.default_options.merge({
  escape_mode: :ascii
})
```

**Comment by krainboltgreene** [comment]
Check out the rewrite and let me know what you think.

**Comment by ohler55** [comment]
No worries.

I like it better but as long as there is a re-org going on how about moving the Installation section to right under the Using section. After that do into the description. Add a Description heading or something to that effect. Description doesn't feel like exactly the right term.

The on the section for describing options, tighten it up so that it is not code but a set of list items. As code lines trail off to the right and it would look nicer with different formatting. Same information but more nicely formatted is better.

**Comment by krainboltgreene** [comment]
Yes! I tend to do using -> installing as well. Very good point.

**Comment by ohler55** [comment]
Are you still working on changes?

**Comment by krainboltgreene** [comment]
Yep, sorry, work has been busy. I'll do it tonight.

**Comment by ohler55** [comment]
Not really a rush. Just checking.

**Comment by krainboltgreene** [comment]
Give the preview a shot, let me know.

**Comment by ohler55** [comment]
It does look cleaner. I like that. I still want to get the options in something other than code so that the descriptions show up without a horizontal scroll. It really doesn't need to be code and would be easier to read if it wasn't. The rest is good to go though.

**Comment by ohler55** [comment]
Are you willing to make the changes? If not I might take what you have done and then change it immediately.

**Comment by ohler55** [comment]
Merged but will change shortly.

**Pull request merged**
