### PR TITLE
Optimize parging option args

### PR DESCRIPTION
**Pull request by Watson1978**
It looked up one by one to make sure that the supported options were included in passed options.
This approach of looking up the passed hash each time has an overhead.

This patch will extract key and value from the passed options using `rb_hash_foreach()` and check if they are supported or not.

−               | before   | after    | result
--               | --       | --       | --
Oj.load          | 381.671k | 419.917k | 1.10x
Oj.dump          | 507.221k | 578.877k | 1.14x

### Environment
- MacBook Air (M1, 2020)
- macOS 12.0 beta 3
- Apple M1
- Ruby 3.0.2

### Before
```
Warming up --------------------------------------
             Oj.load    38.287k i/100ms
             Oj.dump    51.076k i/100ms
Calculating -------------------------------------
             Oj.load    381.671k (± 0.6%) i/s -      1.914M in   5.015868s
             Oj.dump    507.221k (± 0.5%) i/s -      2.554M in   5.035014s
```

### After
```
Warming up --------------------------------------
             Oj.load    42.352k i/100ms
             Oj.dump    58.022k i/100ms
Calculating -------------------------------------
             Oj.load    419.917k (± 0.5%) i/s -      2.118M in   5.043048s
             Oj.dump    578.877k (± 0.4%) i/s -      2.901M in   5.011700s
```

### Test code
```ruby
require 'benchmark/ips'
require 'oj'

json =<<-EOF
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Person",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "The person's first name."
    },
    "lastName": {
      "type": "string",
      "description": "The person's last name."
    },
    "age": {
      "description": "Age in years which must be equal to or greater than zero.",
      "type": "integer",
      "minimum": 0
    }
  }
}
EOF

Benchmark.ips do |x|
  x.report('Oj.load') { Oj.load(json, symbol_keys: true) }

  data = Oj.load(json, symbol_keys: true)
  x.report('Oj.dump') { Oj.dump(json, mode: :compat) }
end
```

### CODE REVIEW

**Comment by ohler55** [comment]
Can we count on the symbols always being the same? In other words, could they change or all they always interned?

**Comment by Watson1978** [comment]
Unlike objects such as strings, the same symbol will be assigned to a unique address.
Therefore, the id of the Symbol object will also be unique.

```
irb(main):001:0> "foo".object_id
=> 260
irb(main):002:0> "foo".object_id
=> 280
irb(main):003:0> :foo.object_id
=> 2192668
irb(main):004:0> :foo.object_id
=> 2192668
```

However, it may be safer to compare the values converted by SYM2ID().

**Comment by ohler55** [comment]
If IDs are assured to be the same when the content is the same for the life of the program then that might be better.

**Comment by Watson1978** [comment]
Since we use rb_gc_register_address() to register the symbol, the symbol will not be freed.

Here is one of using `rb_gc_register_address()`.
https://github.com/ohler55/oj/blob/62aea593dcd7c2102600eeb8dd244f1b39e4088d/ext/oj/oj.c#L1881

OK, I will update PR to use IDs.

**Comment by ohler55** [comment]
As long as the symbols or IDs don't change I'm okay with either one.

**Comment by Watson1978** [comment]
> As long as the symbols or IDs don't change I'm okay with either one.

Thanks. I'm going to quit updating to use IDs.
We have already compared Symbol directly in several places.

https://github.com/ohler55/oj/blob/62aea593dcd7c2102600eeb8dd244f1b39e4088d/ext/oj/oj.c#L1063-L1076

**Comment by ohler55** [comment]
ok

**Comment by Watson1978** [comment]
Ops, I found the mistake in `Test code` in description.

- ❌`Oj.dump(json, mode: :compat)`
- ✅`Oj.dump(data, mode: :compat)`

I should pass `data` instead of `json` string...

**Comment by Watson1978** [comment]
OK, I retake the result.


−               | before   | after    | result
--               | --       | --       | --
Oj.load          | 387.405k | 420.518k | 1.09x
Oj.dump          | 601.762k | 705.901k | 1.17x

### Before
```
Warming up --------------------------------------
             Oj.load    38.675k i/100ms
             Oj.dump    60.591k i/100ms
Calculating -------------------------------------
             Oj.load    387.405k (± 0.9%) i/s -      1.972M in   5.091756s
             Oj.dump    601.762k (± 0.7%) i/s -      3.030M in   5.034717s
```

### After
```
Warming up --------------------------------------
             Oj.load    42.372k i/100ms
             Oj.dump    70.934k i/100ms
Calculating -------------------------------------
             Oj.load    420.518k (± 0.3%) i/s -      2.119M in   5.038126s
             Oj.dump    705.901k (± 0.3%) i/s -      3.547M in   5.024398s
```

### Test code
```ruby
require 'benchmark/ips'
require 'oj'

json =<<-EOF
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Person",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "The person's first name."
    },
    "lastName": {
      "type": "string",
      "description": "The person's last name."
    },
    "age": {
      "description": "Age in years which must be equal to or greater than zero.",
      "type": "integer",
      "minimum": 0
    }
  }
}
EOF

Benchmark.ips do |x|
  x.report('Oj.load (symbol_keys)') { Oj.load(json, symbol_keys: true) }

  data = Oj.load(json, symbol_keys: true)
  x.report('Oj.dump (compat)') { Oj.dump(data, mode: :compat) }
end
```

**Comment by ohler55** [comment]
The MR was already merged. You will have to create a new branch. I'd like to get the MR I put up merged as well if you can take a look.

**Comment by Watson1978** [comment]
No worries. it is just mistake in Pull Request description.

**Pull request merged**
