### PR TITLE
appveyor.yml

### PR DESCRIPTION
**Pull request by stereobooster**
trying out it

### CODE REVIEW

**Comment by stereobooster** [comment]
```
cd tmp/i386-mingw32/oj/2.2.6
c:\MinGW\bin/make.exe
generating oj-i386-mingw32.def
make: *** No rule to make target '/C/Ruby22/include/ruby-2.2.0/ruby.h', needed by 'cache8.o'.  Stop.
rake aborted!
Command failed with status (2): [c:\MinGW\bin/make.exe...]
C:/projects/oj/vendor/bundle/ruby/2.2.0/gems/rake-compiler-0.9.9/lib/rake/extensiontask.rb:157:in `block (2 levels) in define_compile_tasks'
C:/projects/oj/vendor/bundle/ruby/2.2.0/gems/rake-compiler-0.9.9/lib/rake/extensiontask.rb:156:in `block in define_compile_tasks'
C:/projects/oj/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => test_all => compile => compile:i386-mingw32 => compile:oj:i386-mingw32 => copy:oj:i386-mingw32:2.2.6 => tmp/i386-mingw32/oj/2.2.6/oj.so
(See full trace by running task with --trace)
```

need windows compile expert

**Comment by ohler55** [comment]
I didn't have much success either in the appveyer branch.

**Comment by stereobooster** [comment]
https://github.com/davidfstr/rdiscount/blob/master/appveyor-build.ps1

**Comment by stereobooster** [comment]
I have progress

```
# Running:
......................F.......F.............F.......C:/projects/oj/test/test_object.rb:581: [BUG] Segmentation fault
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
-- Control frame information -----------------------------------------------
c:0024 p:---- s:0106 e:000105 CFUNC  :object_load
c:0023 p:0102 s:0102 e:000101 METHOD C:/projects/oj/test/test_object.rb:581
c:0022 p:0029 s:0096 e:000095 BLOCK  C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:108
c:0021 p:0006 s:0094 e:000093 METHOD C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:205
c:0020 p:0009 s:0090 e:000089 BLOCK  C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:105
c:0019 p:0020 s:0088 e:000087 METHOD C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:256
c:0018 p:0009 s:0084 e:000083 BLOCK  C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:104
c:0017 p:0037 s:0082 e:000081 METHOD C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:331
c:0016 p:0041 s:0075 E:001134 METHOD C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:276
c:0015 p:0009 s:0069 E:001270 METHOD C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:103
c:0014 p:0014 s:0066 e:000065 METHOD C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:778
c:0013 p:0020 s:0060 e:000058 METHOD C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:305
c:0012 p:0014 s:0053 e:000052 BLOCK  C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:293 [FINISH]
c:0011 p:---- s:0050 e:000049 CFUNC  :each
c:0010 p:0010 s:0047 e:000046 BLOCK  C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:292
c:0009 p:0037 s:0045 e:000044 METHOD C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:331
c:0008 p:0024 s:0038 E:00021c METHOD C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:318
c:0007 p:0085 s:0032 E:0023f0 METHOD C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:291
c:0006 p:0013 s:0025 e:000024 BLOCK  C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:152 [FINISH]
c:0005 p:---- s:0022 e:000021 CFUNC  :map
c:0004 p:0042 s:0019 e:000018 METHOD C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:152
c:0003 p:0158 s:0011 e:000010 METHOD C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:129
c:0002 p:0071 s:0005 E:0002dc BLOCK  C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:56 [FINISH]
c:0001 p:0000 s:0002 E:000370 (none) [FINISH]
-- Ruby level backtrace information ----------------------------------------
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:56:in `block in autorun'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:129:in `run'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:152:in `__run'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:152:in `map'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:152:in `block in __run'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:291:in `run'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:318:in `with_info_handler'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:331:in `on_signal'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:292:in `block in run'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:292:in `each'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:293:in `block (2 levels) in run'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:305:in `run_one_method'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:778:in `run_one_method'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:103:in `run'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:276:in `with_info_handler'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest.rb:331:in `on_signal'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:104:in `block in run'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:256:in `time_it'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:105:in `block (2 levels) in run'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:205:in `capture_exceptions'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/minitest-5.8.5/lib/minitest/test.rb:108:in `block (3 levels) in run'
C:/projects/oj/test/test_object.rb:581:in `test_time_early'
C:/projects/oj/test/test_object.rb:581:in `object_load'
-- C level backtrace information -------------------------------------------
```

**Comment by stereobooster** [comment]
Build system itself works, it just have Segmentation fault in tests

**Comment by ohler55** [comment]
Going to be tough to debug. Will look tonight though.

**Pull request merged**
