### PR TITLE
OSx

### PR DESCRIPTION
**Pull request by stereobooster**
trying to build under OSx, not sure if it works

### CODE REVIEW

**Comment by ohler55** [comment]
Good to add to travis although I am on OS X here today. I go back and forth.

**Comment by ohler55** [comment]
Odd the linux version doesn't know about Ruby 2.4.1.

**Comment by stereobooster** [comment]
Well it works with 2.4.0. There is no 2.4.1 for OSx on Travis ci

**Comment by ohler55** [comment]
Score! Got some help last night with appveyor. https://ci.appveyor.com/project/ohler55/oj
```
version: 1.0.{build}-{branch}

image: Visual Studio 2015

environment:
  APPVEYOR_RDP_PASSWORD: fixm3-wtf
  RUBY_VERSION: 23-x64
  #PATH: C:\Ruby%RUBY_VERSION%\bin;C:\Ruby23-x64\DevKit\bin;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1;%PATH%
  PATH: c:\Ruby%RUBY_VERSION%\DevKit\mingw\bin;C:\Ruby%RUBY_VERSION%\bin;C:\Ruby%RUBY_VERSION%\DevKit\bin;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1;%PATH% 
build: off

before_build:
  - ruby -v
  - make -v

build_script:
  - cd C:\projects\oj\ext\oj
  - ruby extconf.rb
  - make
```

**Comment by ohler55** [comment]
If we can stay back at 2.4.0 for OS X and 2.4.1 for others that would be ideal.

**Comment by stereobooster** [comment]
done

**Comment by ohler55** [comment]
Thank you!

**Comment by ohler55** [comment]
I stripped down the appveyor tests for debugging. Very odd behavior where just calling Time.new with any number of arguments crashes. Putting it aside for the weekend or until Wednesday.

**Pull request merged**
