### PR TITLE
ActiveSupport tests

### PR DESCRIPTION
**Pull request by stereobooster**
tell me what else to change

### CODE REVIEW

**Comment by ohler55** [comment]
I can tell already that this will keep me busy for a while getting all the tests to pass.

**Comment by stereobooster** [comment]
Well I ported test for 4.1 and 5.0. There is also 4.2 which is popular. But those tests run for `ActiveSupport`, not `Oj` implementation.

**Comment by ianks** [comment]
@ohler55 I have all of these tests passing (minus a few to html escaping stuff) at https://github.com/ianks/yagni_json_encoder

**Comment by ohler55** [comment]
Very nice. I'm continuing to work on getting 100% rails compatibility with optimization. The encoding is the sticking point today. Should get that dealt with soon.

**Pull request merged**
