### PR TITLE
use Oj::ParseError instead of SyntaxError if no callback and multiplejsons in string

### PR DESCRIPTION
**Pull request by fxfilmxf**
Related to issue #249

### CODE REVIEW

**Comment by stim371** [comment]
:+1: raising a SyntaxError currently breaks code that is expecting a ParseError to be raised if the string can't be parsed.

**Comment by ohler55** [comment]
The changes make sense. I'll merge and take a look at the travis errors before releasing.

**Comment by ohler55** [comment]
My mistake. I should have rejected the pull request. You checked in a binary. That was what was breaking the travis build. Fixed now. Something to keep an eye on in the future though.

**Comment by fxfilmxf** [comment]
Sorry about that, I missed the binary in the PR (it's hard to see). Thanks for spending the time to figure that out.

**Pull request merged**
