### PR TITLE
Compatibility tests

### PR DESCRIPTION
**Pull request by stereobooster**
Do you want me to leave only one commit in this PR? Can do that

### CODE REVIEW

**Comment by stereobooster** [comment]
Tests are in isolated folder, but data file not. Can move them to isolated folder, I do not see big difference here

**Comment by ohler55** [comment]
Lets move test/data_compatibility_rails.rb to isolated. test/data_compatibility_json.rb is good in test since it does not pull in the active gems. I like to run tests in the test dir on new Ruby versions first before confounding the results with stray rails gems.

**Comment by ohler55** [comment]
Can you set up travis to not fail to pull in the Oj gem since that is what is being tested?

**Comment by ohler55** [comment]
BTW, it is nice working with you on this. It's been a long time waiting for some serious rails compatibility.

**Comment by stereobooster** [comment]
@ohler55 check now

**Comment by ohler55** [comment]
Excellent

**Comment by ohler55** [comment]
After merging in master it broke again. Must have been a bad merge. Anyway. I am going to focus on getting the rails and to_json more compatible first if you don't mind taking care of the travis issue.

Have to figure out how to handle the rails vs to_json differences as well.

**Pull request merged**
