### PR TITLE
Make Travis CI build faster

### PR DESCRIPTION
**Pull request by dlackty**
As titled. Hope this help!

### CODE REVIEW

**Comment by ohler55** [comment]
I was a bit slow getting got this. Can you explain what it is faster and if rake is still executed?

**Comment by dlackty** [comment]
So for this part:
```yml
sudo:
  false
```

This will make Travis CI use newer and faster container-based environment to build the project, as stated in their [official announcement](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/).

and this line:

```yml
cache:
  bundler
```

would cache bundle-installed packages from build to build, and thus save time from downloading bundled gems every time.

**Comment by ohler55** [comment]
Sounds good. How about the removal of
-script:
-  - bundle exec rake

**Comment by dlackty** [comment]
As stated in [Travis CI Documentation](http://docs.travis-ci.com/user/languages/ruby/#Default-Test-Script):

> Travis CI runs rake by default to execute your tests.

**Comment by ohler55** [comment]
Thanks

**Comment by ohler55** [comment]
fat fingers, in now

**Pull request merged**
