### PR TITLE
[WIP] Fix stream writer output encoding issue

### PR DESCRIPTION
**Pull request by PikachuEXE**
Related issue: https://github.com/malomalo/turbostreamer/pull/6

I am trying to build JSON response with `StreamWriter`
But the output (received by `#write`) has encoding `ASCII-8BIT`
Instead of encoding `UTF-8` from input

### CODE REVIEW

**Comment by ohler55** [comment]
What new feature or fix are you trying to add to Oj?

**Comment by PikachuEXE** [comment]
The output pass to `#write` has encoding `ASCII-8BIT` instead of `UTF-8`
But the input has encoding `UTF-8`

I got a workaround submitted in the related PR for affected gem
But would be great if it can be fixed here

**Comment by ohler55** [comment]
I'll reject the PR but fix the issue.

**Comment by ohler55** [comment]
I opened issue #524 for this. I used your test approach but simplified the test a bit. It was odd behavior as indicated in the issue comment.

Anyway, branch `encoding` has the fix. Please give it a try.

**Comment by ohler55** [comment]
Thanks. I will close the issue once I make a release.

**Pull request closed without merging**
