### PR TITLE
Potential fix for issue 744

### LINKED ISSUE #744: Segfault in parallel processing
I have a system that streams a very large newline oriented JSON into a multiple line chunks and then puts those multiline chunks into a `SizedQueue` which is then processed In separate processes with the [parallel](https://rubygems.org/gems/parallel) gem. Inside those sub processes those lines of json text are parsed with `oj` and we just noticed that we were getting what looks like segmentation faults inside `oj`.

This may have been going on a while, since this is deep inside a much larger system, and at the moment I'm not able to generate an exact test case since this is the middle of processing a few lines of a much larger file. I do have ruby segfault traces though. Here is one of them. This is on oj 3.13.11 with ruby 2.7.3. on Ubuntu 18.04.

I'm happy to attempt some experiments if there are any pointers that may be needed or answer any questions. Since this happens fairly infrequently with relation to the data volume, I'm shooting in the dar here and guessing that this probably has to do with a  combination of possibly some malformed json + reuse of some C structure + parallel processing with copy on write.

```
/ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0010 p:---- s:0060 e:000059 CFUNC  :fork
c:0009 p:0048 s:0056 e:000055 METHOD /ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456
c:0008 p:0045 s:0044 e:000040 BLOCK  /ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:440 [FINISH]
c:0007 p:---- s:0036 e:000035 CFUNC  :synchronize
c:0006 p:0009 s:0032 e:000031 METHOD /ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:433
c:0005 p:0060 s:0023 e:000022 BLOCK  /ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:404 [FINISH]
c:0004 p:---- s:0016 e:000015 CFUNC  :loop
c:0003 p:0034 s:0012 e:000011 BLOCK  /ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398
c:0002 p:0005 s:0006 e:000005 BLOCK  /ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:222 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:222:in `block (4 levels) in in_threads'
/ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in `block (2 levels) in work_in_processes'
/ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in `loop'
/ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:404:in `block (3 levels) in work_in_processes'
/ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:433:in `replace_worker'
/ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:433:in `synchronize'
/ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:440:in `block in replace_worker'
/ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `worker'
/ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `fork'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f113a8e6910 RBP: 0x000055c81250c840 RSP: 0x00007f110a4f0da8
 RAX: 0x0000000000000000 RBX: 0x00007f1128f12d90 RCX: 0x00007f1128f12d80
 RDX: 0x00007f112bd6e530 RDI: 0x00007f1128f12d90 RSI: 0x0000000000000001
  R8: 0x000055c81250ca50  R9: 0x000000549e773d2b R10: 0x0000000000000000
 R11: 0x0000000000000000 R12: 0x000055c81253ad88 R13: 0x00007f110a4f0e10
 R14: 0x000055c81250deb0 R15: 0x000055c81250c840 EFL: 0x0000000000010246

-- C level backtrace information -------------------------------------------
2022-01-16T04:18:49Z 10036  INFO : Worker 22 start processing 76D258 with 107 events
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_vm_bugreport+0x7ce) [0x7f113aee81de] vm_dump.c:755
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_bug_for_fatal_signal+0xe7) [0x7f113ad078f7] error.c:660
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(sigsegv+0x4b) [0x7f113ae4c06b] signal.c:946
/lib/x86_64-linux-gnu/libc.so.6(0x7f113a88b040) [0x7f113a88b040]
/lib/x86_64-linux-gnu/libc.so.6(malloc_usable_size+0x40) [0x7f113a8e6910]
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(objspace_xfree+0x5) [0x7f113ad2c472] gc.c:9694
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(ruby_sized_xfree) gc.c:10178
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(ruby_xfree) gc.c:10185
/ebs/apps/navpass/navpass-core/shared/bundle/ruby/2.7.0/gems/oj-3.13.11/lib/oj/oj.so(free_doc_cb+0x21) [0x7f112bd6e5b1] fast.c:673
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(run_final+0xb) [0x7f113ad25869] gc.c:3372
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(finalize_list) gc.c:3391
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_objspace_call_finalizer+0x2f0) [0x7f113ad32540] gc.c:3536
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_ec_finalize+0x2d) [0x7f113ad14f6e] eval.c:152
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_ec_cleanup) eval.c:256
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(ruby_stop+0x9) [0x7f113ad15129] eval.c:290
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_f_fork+0x74) [0x7f113adfbd74] process.c:4158
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_call_cfunc_with_frame+0xc9) [0x7f113aec484a] vm_insnhelper.c:2514
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_call_cfunc) vm_insnhelper.c:2539
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_sendish+0x58) [0x7f113aecff6d] vm_insnhelper.c:4023
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_exec_core) insns.def:782
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_vm_exec+0xab) [0x7f113aed629b] vm.c:1920
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(invoke_iseq_block_from_c+0x98) [0x7f113aed6f8e] vm.c:1116
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(invoke_block_from_c_bh) vm.c:1134
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_yield) vm.c:1179
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_yield_0) vm_eval.c:1227
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_yield_1) vm_eval.c:1233
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_yield) vm_eval.c:1243
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_ensure+0xd4) [0x7f113ad126e4] eval.c:1129
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_call_cfunc_with_frame+0xc9) [0x7f113aec484a] vm_insnhelper.c:2514
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_call_cfunc) vm_insnhelper.c:2539
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_sendish+0x58) [0x7f113aecff6d] vm_insnhelper.c:4023
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_exec_core) insns.def:782
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_vm_exec+0xab) [0x7f113aed629b] vm.c:1920
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(invoke_block+0x153) [0x7f113aee260f] vm.c:1044
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(invoke_iseq_block_from_c) vm.c:1116
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(invoke_block_from_c_bh) vm.c:1134
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_yield) vm.c:1179
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_yield_0) vm_eval.c:1227
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(loop_i) vm_eval.c:1330
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_vrescue2+0xd1) [0x7f113ad121b1] eval.c:990
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_rescue2+0x8a) [0x7f113ad123aa] eval.c:967
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_call_cfunc_with_frame+0xc9) [0x7f113aec484a] vm_insnhelper.c:2514
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_call_cfunc) vm_insnhelper.c:2539
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_sendish+0x58) [0x7f113aecff6d] vm_insnhelper.c:4023
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_exec_core) insns.def:782
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_vm_exec+0xab) [0x7f113aed629b] vm.c:1920
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(invoke_iseq_block_from_c+0x183) [0x7f113aeda263] vm.c:1116
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(invoke_block_from_c_proc) vm.c:1216
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(vm_invoke_proc) vm.c:1238
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_vm_invoke_proc) vm.c:1259
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(thread_do_start+0x289) [0x7f113ae8fe09] thread.c:692
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(thread_start_func_2+0x257) [0x7f113ae92187] thread.c:740
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(rb_native_cond_initialize+0x0) [0x7f113ae927bb] thread_pthread.c:969
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(register_cached_thread_and_wait) thread_pthread.c:1021
/opt/rbenv/versions/2.7.3/lib/libruby.so.2.7(thread_start_func_1) thread_pthread.c:976
/lib/x86_64-linux-gnu/libpthread.so.0(start_thread+0xdb) [0x7f113a4176db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f113a96d71f]
```

### PR DESCRIPTION
**Pull request by copiousfreetime**
This is a potential fix for #744 - and includes a test case that fails on my laptop. See [`test/test_744.rb`](https://github.com/copiousfreetime/oj/blob/bugfix/issue-744/test/test_744.rb) and the notes in it. 

I don't expect this PR to be merged as is, as there is a fairly large data file now in the test directory so others can attempt to replicate the issue.

I have 2 branches
-  [bugfix/issue-744](https://github.com/copiousfreetime/oj/tree/bugfix/issue-744) which is  just the newly added test
- [bugfix/issue-744-patch](https://github.com/copiousfreetime/oj/tree/bugfix/issue-744-patch) which is 1 more commit a40725c08fb563cd24d881a96950d80fc4ae1bcd which fixes the issue for me.

This is mostly a guideline for discussion to figure out the proper solution

### CODE REVIEW

**Comment by ohler55** [comment]
Can you set up the test to generate the needed files instead of adding the huge files to the repo?

I assure that running the test will fail without your changes.

**Comment by copiousfreetime** [comment]
I wanted to see if this was an acceptable solution approach that would work for the project before seeing if I can generate data that causes it to failure. That might take a bit more time. I'm willing to do that, and actually what I would want to be in there too.

I'd like to see if someone else can replicate the failure. Did checking out [`bugfix/issue-744`](https://github.com/copiousfreetime/oj/tree/bugfix/issue-744) fail for you? Just running `bundle install && bundle exec rake compile && bundle exec ruby test/test_744.rb` blow up for you?

**Comment by ohler55** [comment]
Sorry for the delay. I tested before and after. You fix, as expected, indeed fixes the issue. If you can clean up the dependencies and large files I'd be glad to merge. Thanks for helping out.

**Comment by ohler55** [comment]
I think this was already taken care of. Okay to close?

**Comment by copiousfreetime** [comment]
@ohler55 is there another commit that does a similar thing on main? I’ve been away for a while - and I’ll be doing a fair bit of performance testing this week on the codebase that this error appears, so I can see if it is fixed in another version.

**Comment by copiousfreetime** [comment]
@ohler55 oh I see 7280870c544767ab6f646495458836e67cc6803c - I’ll test the latest version this week and confirm.

**Comment by ohler55** [comment]
If I'm mistaken (always possible) this PR can be reopened. I thought it got taken care of in a slightly different way. I'll wait you for your check.

**Comment by copiousfreetime** [comment]
@ohler55 I kicked off some long running processes using version ec9f0d175f3cefa11b322d2146327e9251199e02 and after running for almost an hour, they all get OOMKilled by linux. The only change i made to the codebase from the what wsa running yesterday was bump oj from 3.11.2 to ec9f0d175f3cefa11b322d2146327e9251199e02. Rolling back to 3.11.2 and seeing if things work just fine.

**Comment by ohler55** [comment]
Did you mean 3.11.2 or the latest version? I guess it is okay though unless Oj is the cause of the out of memory error in which case there is a different issue to address. Right?

**Comment by copiousfreetime** [comment]
I had my system running with oj 3.11.2 which had the the issue that sometimes, it would segfault. 

I updated only oj to ec9f0d1, as in that was the only thing that changed between for this additional run and the ec2 instance fell over with an oomkiller error against the ruby process (after about an hour of running). (had to hard reboot).

I did this 3 times just to make sure that it wasn't a fluke - oomkiller all 3 times.

So I rolled back my system to use 3.11.2 which has the known issue of sometimes segfaulting - and the runs all went normally (randomly segfaulting).

I'm fairly confident that this means there is a memory leak in in ec9f0d1. It may only arise when used oj is used across forked processes.

**Comment by ohler55** [comment]
Okay, will look into it and see if your changes fix it. Thanks

**Comment by copiousfreetime** [comment]
@ohler55 I'll plan on doing a long run against my patch before the end of next week too.

**Comment by copiousfreetime** [comment]
Well - unfortunately - it looks like my patch also suffers from the same long-term memory leak/reference leak. its takes about an hour of continually running, but it also gets oom-killed. So for the moment I would not commit my patch, and I would also back out your version of the same fix. I'm not sure if I'll be able to figure this one in the next week or so.

**Comment by ohler55** [comment]
ok, I'll do some cleanup.

**Comment by ohler55** [comment]
Are you able to share your test setup?

**Comment by copiousfreetime** [comment]
The trimmed down version of the code is what I have in my PR in https://github.com/copiousfreetime/oj/blob/bugfix/issue-744-patch/test/test_744.rb and the data in https://github.com/copiousfreetime/oj/tree/bugfix/issue-744-patch/test/test_744-data - although I haven't tried this test on the production level infrastructure, I'm going to do that this week.  

The machine I'm running this on is an AWS r5.8xlarge - so 258GB of ram and 32 cpus - and while proccessing a file, this machines cpus are fully saturated using the parallel gem

* OS - ubuntu 20.04
* Ruby - 2.7.7 
* rubygems - 3.1.6
* bundler 2.4.3

The files that get processed are in the format of https://github.com/copiousfreetime/oj/blob/bugfix/issue-744-patch/test/test_744-data/small-dataset - but each one is much larger, its generally 6-14GB in size, and 5-10 Million rows in length.

It looks like on my side that the process is getting oomkilled after processing about 3 files so after approximately 30 million rows of data.

My next steps are:

- probably change the code to die and get restarted after processing a single file instead of pipelineing one file after another
- see if the performance of using the fast parser is still there for my use case - and if not - stop using it
- try the test script out and see if I can catch the memory leak in progress - or at least get it oomkilled

**Comment by ohler55** [comment]
If you really want to get crazy my agoo repo has a debug.h and debug.c file that sets up a memory tracking system. Oj is not set up to use that but with some grepping and replacing it could me made to identify leaks. I can take a look at that and see if I can get Oj modified or at least on a branch.

**Comment by ohler55** [comment]
I have a "mem-debug" branch that might be helpful. If you add a `-DMEM_DEBUG` to the cflags in the Makefile and then call Oj.mem_report periodically you will see memory in use. It will be slower and will use more memory but it can be useful for tracking memory use issues.

**Pull request closed without merging**
