### PR TITLE
Cache C compilation using ccache in Travis

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by thedrow** [comment]
Hold on with this one. It says that nothing is changed.

**Comment by ohler55** [comment]
Check my response to the issue. Use combat mode if you want a string returned. The JSON format for object is not the same as combat mode.

**Comment by ohler55** [comment]
Whats the latest on this?

**Comment by thedrow** [comment]
You can merge this if you want to.

**Comment by ohler55** [comment]
Thanks.

**Pull request merged**
