### PR TITLE
Preliminary fix for #244

### PR DESCRIPTION
**Pull request by asurin**
@ohler55 I've made a preliminary attempt at fixing issue #244 .  I've added a new test case (Although it might be worth merging into _test_active_mimic.rb.  I'm very open to any feedback on the C changes/style as my C's pretty rusty.  I've also made on small language fix to design.txt

### CODE REVIEW

**Comment by ohler55** [comment]
I'll have to go over the code first. First look it seems good though. Other than the requirement for sqlite3. Can you get rid of that requirement? Travis tests need to pass as well but if you can get rid of the requirement for sqlite3 they should pass I think.

**Comment by asurin** [comment]
To give a little background on the issue from a Rails-centric point of view.

Most Rails' objects serialize via. two steps.  Generally, the developer will call `to_json` to actually generate the serialized data.  Internally, `to_json` will invoke `as_json`, which returns a hash containing json-compatible (basic types, or objects that also respond to an `as_json` call) objects that it can then serialize.

It looks like the JSON gem allows arbitrary parameters to be passed to `to_json`, which should then be passed through to `as_json` intact.  Oj was always invoking `as_json` without the params passed to `to_json` when it replaced it.  This patch should ensure the parameters are passed through to the internal `as_json` methods

**Comment by asurin** [comment]
Yup, 100% - I'll remove that now!

**Comment by ohler55** [comment]
you are a star, thanks.

**Comment by asurin** [comment]
@ohler55 hmmm..it looks like ActiveRecord requires a DB adapter,a dn because this is testing the rails integration it'll break if I remove AR.  I copied the require from _test_active.rb - I'm guessing the underscore is so minitest ignores it?  (I'll confess I've mainly used rspec in the past).  I've renamed that test with an underscore too, in the hopes that it'll stop that test from being included, but I'm also 100% good with just deleting the test entirely

**Comment by ohler55** [comment]
Maybe call to_json with arguments and make sure they are used in the object to_json or as_json.

**Comment by asurin** [comment]
Ah good idea!  I'll get that coded up this evening or early tomorrow and added to the PR.  That'll let me slim the test down a lot - thanks for the advice!

**Comment by asurin** [comment]
@ohler55 this test should now not depend on Rails, and instead explicitly test the passthrough from `to_json` to `as_json`

**Comment by ohler55** [comment]
Great. I'll look and merge tomorrow. Thank you.

**Comment by asurin** [comment]
Sounds great - thanks for your help with all this!

**Comment by ohler55** [comment]
Looks good. Thanks. It will be released soon.

**Comment by ohler55** [comment]
Did a little cleanup. Release will go out assuming travis is happy.

**Comment by asurin** [comment]
Awesome - thanks for the help and the quick turnaround.  Really appreciate it!

**Comment by ohler55** [comment]
I'd have to turn that around and thank you for getting the fix in.

**Comment by asurin** [comment]
No worries at all, glad to help :)

**Comment by chancedowns** [comment]
:+1:

**Pull request merged**
