### PR TITLE
Add rubocop and rubocop-minitest deps

### PR DESCRIPTION
**Pull request by nschonni**
Add the rubocop and rubocop-minitest dependencies, and regen the todos. Flipped the CI job to used the dependencies

### CODE REVIEW

**Review by ohler55 — APPROVED** [review]

**Comment by nschonni** [comment]
Odd, don't know why the TruffleRuby test is failing again

**Comment by ohler55** [comment]
Odd indeed.

**Comment by nschonni** [comment]
Flipped to draft since it's still failing after rebasing and trying a few things with the matrix. I'll rebase after https://github.com/ohler55/oj/pull/858

**Comment by nschonni** [comment]
Don't know why it fixed it, but moving it over to the Gemfile appears to keep TruffleRuby happy. Not sure if there was some sort of loading something it didn't like, so I made sure it had the `require: false`, which doesn't appear to be possible with `add_development_dependency`

**Comment by ohler55** [comment]
Nice. Once the merge conflict is resolved I'll merge.

**Comment by nschonni** [comment]
Rebased for the conflicts. Noticed there was a new Rubocop version so i regenerated the todo again

**Comment by ohler55** [comment]
Tough one, thank you.

**Pull request merged**
