### PR TITLE
fix duplicate test names in test_compat.rb

### PR DESCRIPTION
**Pull request by mqchau**
Fixes https://github.com/ohler55/oj/issues/635

### CODE REVIEW

**Comment by ohler55** [comment]
I'll merge after tests complete on travis assuming nothing fails.

**Comment by mqchau** [comment]
When is it supposed to run? It's been 30 mins and it didn't start yet?

On a side note: are you happy with Travis? If not I can look into migrating to Github Actions.

**Comment by ohler55** [comment]
Sadly travis gets bogged down quiet often. I'll keep on checking back though. I presume all passed when you ran the tests.

**Comment by ohler55** [comment]
No need for a release for this but it will be used on all future testing. Thank you. Sharp eye.

**Pull request merged**
